# Change these first
owner: the2hill # Your GitHub organization or username, where this repository lives
repo: rs-flex-uptime # The name of this repository

sites:
  - name: nova-api
    url: https://nova.api.sjc3.rackspacecloud.com
  - name: neutron-probe
    url: https://neutron.api.sjc3.rackspacecloud.com
  - name: keystone-probe
    url: https://keystone.api.sjc3.rackspacecloud.com/v3
  - name: octavia-probe
    url: https://octavia.api.sjc3.rackspacecloud.com
  - name: glance-probe
    url: https://glance.api.sjc3.rackspacecloud.com
  - name: heat-probe
    url: https://heat.api.sjc3.rackspacecloud.com
  - name: cinder-probe
    url: https://cinder.api.sjc3.rackspacecloud.com
  - name: cloudformation-probe
    url: https://cloudformation.api.sjc3.rackspacecloud.com
  - name: placement-probe
    url: https://placement.api.sjc3.rackspacecloud.com
  - name: barbican-probe
    url: https://barbican.api.sjc3.rackspacecloud.com
  - name: magnum-probe
    url: https://magnum.api.sjc3.rackspacecloud.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /rs-flex-uptime
  logoUrl: https://docs.rackspacecloud.com/assets/images/rackspace_logo-white.svg
  favicon: https://docs.rackspacecloud.com/assets/images/pngegg.png
  themeUrl: https://the2hill.github.io/rs-flex-uptime/flex.css
  name: Flex Cloud Status
  introTitle: "API Monitoring"
  #introMessage:
  navbar:
    - title: Status
      href: /
    - title: Genestack GitHub
      href: https://docs.rackspacecloud.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Rackspace
      href: https://rackspace.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
